### ISSUE TITLE
Add a function to calculate legal moves for a piece

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#23]

**Comment by ShiranLiu** [comment]
aa3646d888a342eb9fa64c1d56ad1f590419b267

**Comment by ShiranLiu** [comment]
423387a1c4a97863c1ec52019f8c8fb9f2a03a97
3c5ece85802aa390829c0c4426cf605ef9c5d615
2cbd39736eed6068371e65700832b07e47fa2cbe
