### ISSUE TITLE
design of Room class in the game part of backend (tentative version)

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#27]

**Comment by ShiranLiu** [comment]
Users can join and quit a room. Room instance knows which users are in the room or quite the room via userId variable (i.e. manipulates with int userId)

**Comment by ShiranLiu** [comment]
- [] aaa

**Comment by stefanpluess** [comment]
[aa3646d](https://github.com/sopra-fs23-group-22/sopra-fs23-group-22-server/commit/aa3646d888a342eb9fa64c1d56ad1f590419b267)
