### ISSUE TITLE
mechanism and function to check players are ready to start the game (i.e. both have completed the placement of initial board) (tentative version)

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#49]

**Comment by ShiranLiu** [comment]
- [ ] implementation of the design of Room class (tentative version, requires integration test to confirm final design)
- [ ] connection between front-end and back-end to receive the request when both players are ready

**Comment by ShiranLiu** [comment]
aa3646d888a342eb9fa64c1d56ad1f590419b267
50bac5a13d6c654f96be100eab56939e3827c7b6
30e41779ee137df62b860c3e012110978b6277d1
5533b010cc1e2d2559a62965aaf27c9ac59a218a
374aba30d090b1dd65af4f4910a4da41599609b3
