### ISSUE TITLE
corporation between front-end and back-end to perform the placement of initial board

### ISSUE THREAD

**Issue by ShiranLiu** [sopra-fs23-group-22/sopra-fs23-group-22-server#83]

**Comment by jiachencindybao** [comment]
ded22615aa42ce8481009aa411b78d3e040e4f7c
A preliminary version of the endpoint for placing the initial board

**Comment by jiachencindybao** [comment]
c2c2e3d4950361240b78c57141edc6be1af1a690
Added DTO of piece, square and board
