### ISSUE TITLE
move strategies for different piece types (Strategy Design Pattern) (tentative version)

### ISSUE THREAD

**Issue by ShiranLiu** [sopra-fs23-group-22/sopra-fs23-group-22-server#84]

**Comment by ShiranLiu** [comment]
MOVE
basic: <-- applicable to pieces other than Bomb, Flag, Scout
- only 1 space
- target should be BATTLE_FIELD & no content
bomb:
- cannot move
flag
- cannot move
scout:
- may move any number of spaces
- straight line
- the squares of the track should have no content & should not be lake

**Comment by stefanpluess** [comment]
[aa3646d](https://github.com/sopra-fs23-group-22/sopra-fs23-group-22-server/commit/aa3646d888a342eb9fa64c1d56ad1f590419b267)
